import { Href, usePathname, useRouter } from 'expo-router';
import { ReactNode } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';

export const colors = { cream: '#F8F5EE', paper: '#FFFDF8', ink: '#20251F', muted: '#73786F', line: '#E5E2D8', green: '#2F5D50', gold: '#B88645' };
const tabs = [{ label: 'Home', icon: '⌂', route: '/(app)/home' }, { label: 'Discover', icon: '⌕', route: '/(app)/discover' }, { label: 'Create', icon: '+', route: '/(app)/create' }, { label: 'Activity', icon: '♡', route: '/(app)/activity' }, { label: 'Messages', icon: '□', route: '/(app)/messages' }, { label: 'Profile', icon: '○', route: '/(app)/profile' }] as const;
export function AppShell({ children, title, action }: { children: ReactNode; title: string; action?: ReactNode }) { const router = useRouter(); const pathname = usePathname(); return <SafeAreaView style={styles.safe}><View style={styles.header}><Text style={styles.wordmark}>HOLY WAY</Text><View style={styles.headerRow}><Text style={styles.title}>{title}</Text>{action}</View></View><View style={styles.content}>{children}</View><View style={styles.nav}>{tabs.map((tab) => { const active = pathname.includes(tab.route.split('/').pop() || 'home'); return <Pressable key={tab.label} onPress={() => router.replace(tab.route as Href)} style={styles.navItem}><Text style={[styles.navIcon, active && styles.navActive]}>{tab.icon}</Text><Text style={[styles.navLabel, active && styles.navActive]}>{tab.label}</Text></Pressable>; })}</View></SafeAreaView>; }
export function SectionLabel({ children }: { children: ReactNode }) { return <Text style={styles.section}>{children}</Text>; }
export const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.cream }, header: { paddingHorizontal: 22, paddingTop: 14, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: colors.line }, wordmark: { color: colors.gold, fontSize: 12, fontWeight: '800', letterSpacing: 2 }, headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 }, title: { color: colors.ink, fontSize: 30, fontWeight: '700' }, content: { flex: 1, paddingHorizontal: 20 }, nav: { flexDirection: 'row', backgroundColor: colors.paper, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 9, paddingBottom: 7 }, navItem: { flex: 1, alignItems: 'center', gap: 2 }, navIcon: { color: colors.muted, fontSize: 23, lineHeight: 25 }, navLabel: { color: colors.muted, fontSize: 10, fontWeight: '600' }, navActive: { color: colors.green }, section: { color: colors.gold, fontSize: 12, fontWeight: '800', letterSpacing: 1.5, textTransform: 'uppercase', marginBottom: 12 }, card: { backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, padding: 18, marginBottom: 14 }, body: { color: colors.muted, fontSize: 15, lineHeight: 23 }, button: { backgroundColor: colors.green, paddingVertical: 14, alignItems: 'center' }, buttonText: { color: '#FFFFFF', fontWeight: '700' } });
